/**
 * Generates work/<slug>.html for every project and rewrites the work section of index.html
 * between the WORK:START and WORK:END markers. Run after editing content/projects.mjs:
 *   npm run build:work
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { projects, filters, changelog } from '../content/projects.mjs';
const now = JSON.parse(readFileSync(new URL('../content/now.json', import.meta.url), 'utf8'));

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);
const keysFor = (tags) => filters.filter((f) => f.key === 'all' || f.tags.some((t) => tags.includes(t))).map((f) => f.key).join(' ');
const lead = (p) => p.metrics[0];
const seoTitle = (p) => `${p.seo_title || p.title} · Nimit Jain`;

/* ---------------- index section ---------------- */
const indexRows = projects.map((p, i) => {
  const m = lead(p);
  const idx = String(i + 1).padStart(2, '0');
  return `        <article class="prow" data-keys="${keysFor(p.tags)}" data-shot="assets/img/${p.shots[0].file}" data-reveal>
          <div class="prow-main">
            <h3 class="prow-t"><span class="prow-idx">${idx}</span><a href="work/${p.slug}.html">${esc(p.title)}</a>${p.measured ? `<a class="pill" href="work/${p.slug}.html#measured" title="Has a measured table with sources">measured</a>` : ''}</h3>
            <p class="prow-s">${esc(p.one_line)}</p>
            <div class="prow-meta"><span class="prow-stack">${p.stack.map(esc).join(', ')}</span><ul class="prow-tags">${p.tags.map((t) => `<li>${esc(t)}</li>`).join('')}</ul></div>
            <div class="prow-cta"><a href="work/${p.slug}.html">Case study</a>${p.links.live ? `<a href="${p.links.live}" rel="noopener">Live</a>` : ''}${p.links.repo ? `<a href="${p.links.repo}" rel="noopener">GitHub</a>` : ''}</div>
          </div>
          <div class="prow-r">${m ? `<span class="prow-v">${esc(m.value)}</span><span class="prow-c">${esc(m.label)}</span>` : `<span class="prow-period">${esc(p.period)}</span>`}</div>
        </article>`;
}).join('\n');

const filterChips = filters.map((f) => `<button type="button" class="fchip" data-filter="${f.key}" aria-pressed="${f.key === 'all'}">${esc(f.label)}</button>`).join('');

const changelogRows = changelog.map((c) => `        <div class="cl-row" data-cl data-v="${esc(c.v)}" data-d="${esc(c.date)}"><span class="cl-d"><b>${esc(c.date)}</b> · ${esc(c.what)}<em>${esc(c.learned)}</em></span></div>`).join('\n');
const changelogNums = changelog.map((c) => `<span>${esc(c.v)}</span>`).join('');

const workSection = `    <!-- WORK:START (generated by scripts/build-work.mjs from content/projects.mjs; do not edit by hand) -->
    <section class="sec" id="work">
      <header class="sec-head">
        <h2 class="sec-title" data-mask>Work</h2>
        <p class="sec-lede">${projects.length} projects. A <span class="pill pill-static">measured</span> mark means the case study has a table of numbers with their sources.</p>
      </header>
      <div class="filters" role="group" aria-label="Filter projects">${filterChips}<span class="fcount" data-shown>${projects.length} shown</span></div>
      <div class="plist" data-project-list>
${indexRows}
      </div>
      <p class="more" data-reveal>Also live:
        <a class="uline" href="https://reactui-businesswebapp-nimit.netlify.app/">Business Web App</a>,
        <a class="uline" href="https://cultural-club1.vercel.app/">Cultural Club for Vedam</a>,
        <a class="uline" href="https://nimits-clicky-projects.netlify.app/">Clicky Projects</a>,
        <a class="uline" href="https://leetcodeuserextractor.netlify.app/">LeetCode Analytics</a>.
      </p>
    </section>

    <section class="sec" id="changelog">
      <header class="sec-head">
        <h2 class="sec-title" data-mask>Changelog</h2>
        <p class="sec-lede">Shipping since June 2025. One learning per entry, newest first.</p>
      </header>
      <div class="cl" data-changelog>
        <div class="cl-stick"><div class="cl-big" aria-live="polite">${changelogNums}</div><div class="cl-when" data-cl-when>${esc(changelog[0].date)}</div></div>
        <div class="cl-rows"><i class="cl-rail" aria-hidden="true"></i>
${changelogRows}
        </div>
      </div>
    </section>
    <!-- WORK:END -->`;

const idxPath = new URL('../index.html', import.meta.url);
let idx = readFileSync(idxPath, 'utf8');
const s = idx.indexOf('    <!-- WORK:START');
const e = idx.indexOf('    <!-- WORK:END -->');
if (s < 0 || e < 0) throw new Error('WORK:START / WORK:END markers not found in index.html');
idx = idx.slice(0, s) + workSection + idx.slice(e + '    <!-- WORK:END -->'.length);

/* Now line: three fields and a date, from content/now.json. JS turns the date into "updated N days ago". */
const nowLine = `      <!-- NOW:START (generated from content/now.json by scripts/build-work.mjs) -->
      <p class="now" id="now">Right now: building <b>${esc(now.building)}</b>, watching <b>${esc(now.watching)}</b>, reading <b>${esc(now.reading)}</b>. <time class="now-when" datetime="${esc(now.updated)}" data-now-updated>Updated ${esc(now.updated)}</time></p>
      <!-- NOW:END -->`;
const ns = idx.indexOf('      <!-- NOW:START');
const ne = idx.indexOf('      <!-- NOW:END -->');
if (ns < 0 || ne < 0) throw new Error('NOW:START / NOW:END markers not found in index.html');
idx = idx.slice(0, ns) + nowLine + idx.slice(ne + '      <!-- NOW:END -->'.length);
writeFileSync(idxPath, idx);

/* ---------------- case-study pages ---------------- */
mkdirSync(new URL('../work/', import.meta.url), { recursive: true });

const page = (p, i) => {
  const next = projects[(i + 1) % projects.length];
  const idx = String(i + 1).padStart(2, '0');
  const shots = p.shots.map((s) => `        <figure class="shot"><img src="../assets/img/${s.file}" alt="${esc(p.title)}: ${esc(s.caption)}" loading="lazy"><figcaption>${esc(s.caption)}</figcaption></figure>`).join('\n');
  const measured = p.measured ? `      <section id="measured" class="measured">
        <h2>Measured</h2>
        <table>
          <thead><tr><th>Metric</th><th>Value</th><th>Window</th><th>Source</th></tr></thead>
          <tbody>
${p.metrics.map((m) => `            <tr><td>${esc(m.label)}${m.detail ? `<span class="muted">, ${esc(m.detail)}</span>` : ''}</td><td class="num">${esc(m.value)}</td><td class="muted">${esc(m.window)}</td><td class="src">${esc(m.source)}</td></tr>`).join('\n')}
          </tbody>
        </table>
      </section>` : '';
  const phases = p.phases.map((ph) => `      <section class="phase"><h2>${esc(ph.title)}</h2>${ph.body.map((b) => `<p>${esc(b)}</p>`).join('')}</section>`).join('\n');
  const links = [p.links.live && `<a class="uline" href="${p.links.live}" rel="noopener">Live</a>`, p.links.repo && `<a class="uline" href="${p.links.repo}" rel="noopener">Repository</a>`].filter(Boolean).join(' <span class="sep">/</span> ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(seoTitle(p))}</title>
  <meta name="description" content="${esc(p.one_line)}">
  <meta name="theme-color" content="#f4f3ef">
  <link rel="preconnect" href="https://api.fontshare.com" crossorigin>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet">
  <link href="https://api.fontshare.com/v2/css?f[]=switzer@400,500,600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../css/app.css?v=19">
  <link rel="stylesheet" href="../css/grid.css?v=19">
</head>
<body class="page-cs">
  <header class="nav">
    <a class="nav-brand" href="../index.html">Nimit Jain</a>
    <nav class="nav-links" aria-label="Primary">
      <a href="../index.html#work" class="on">Work</a>
      <a href="../index.html#creator">Creator</a>
      <a href="../index.html#about">About</a>
      <a href="../index.html#contact">Contact</a>
    </nav>
    <a class="nav-ask" href="../index.html#contact">Get in touch</a>
  </header>
  <main>
    <article class="cs">
      <header class="cs-head">
        <p class="crumb"><a href="../index.html#work">Work</a> · ${idx}</p>
        <h1>${esc(p.title)}</h1>
        <p class="cs-lead">${esc(p.one_line)}</p>
        <dl class="cs-meta">
          <div><dt>Role</dt><dd>${esc(p.role)}</dd></div>
          ${p.team.length ? `<div><dt>Team</dt><dd>${p.team.map(esc).join(', ')}</dd></div>` : ''}
          <div><dt>Period</dt><dd>${esc(p.period)}</dd></div>
          <div><dt>Status</dt><dd>${esc(p.status)}</dd></div>
          <div class="wide"><dt>Stack</dt><dd>${p.stack.map(esc).join(', ')}</dd></div>
          ${links ? `<div class="wide"><dt>Links</dt><dd>${links}</dd></div>` : ''}
        </dl>
      </header>
      <div class="shots">
${shots}
      </div>
${measured}
${phases}
      ${p.learned ? `<p class="learned"><span class="muted">Learned:</span> ${esc(p.learned)}</p>` : ''}
      <nav class="next" aria-label="Next project"><span class="muted">Next</span><a href="${next.slug}.html">${esc(next.title)}<span class="muted"> · ${esc(next.one_line)}</span></a></nav>
    </article>
  </main>
  <div class="cur" id="cur" aria-hidden="true"></div>
  <script src="../js/cursor.js?v=19"></script>
  <script src="../js/cs.js?v=19"></script>
</body>
</html>
`;
};

for (const [i, p] of projects.entries()) writeFileSync(new URL(`../work/${p.slug}.html`, import.meta.url), page(p, i));
console.log(`work: index section rewritten, ${projects.length} case-study pages written to work/`);
